#ifndef __MISSDESKTOPTOOLS__
#define __MISSDESKTOPTOOLS__

/**
@file
Subclass of DesktopToolsBase, which is generated by wxFormBuilder.
*/

#include "..\Generated\GUIFrame.h"

#include <memory>

//// end generated include

/** Implementing DesktopToolsBase */
class MissDesktopTools : public DesktopToolsBase
{
    class Impl;
	public:
		/** Constructor */
		MissDesktopTools( wxWindow* parent );
	//// end generated class members
	
protected:
    void InitUi();

private:
    std::tr1::shared_ptr<Impl> m_pImpl;
};

#endif // __MISSDESKTOPTOOLS__
