#ifndef __MissAbout__
#define __MissAbout__

/**
@file
Subclass of AboutBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing AboutBase */
class MissAbout : public AboutBase
{
	public:
		/** Constructor */
		MissAbout( wxWindow* parent );
	//// end generated class members
	
};

#endif // __MissAbout__
