#ifndef __MISSHOTKEYSETTING__
#define __MISSHOTKEYSETTING__

/**
@file
Subclass of HotKeySettingBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing HotKeySettingBase */
class MissHotKeySetting : public HotKeySettingBase
{
public:
    /** Constructor */
    MissHotKeySetting(const wxString& strHotKey, wxWindow* parent );
    ~MissHotKeySetting();

    void GetHotKeyString(wxString& strHotKey);

protected:
    void BindEvent();
    void UnbindEvent();

    // Handlers for HotKeySettingBase events.
    void OnBtnClearClick( wxCommandEvent& event );



};

#endif // __MISSHOTKEYSETTING__
