#ifndef __MissHotKeyFrame__
#define __MissHotKeyFrame__

/**
@file
Subclass of MissHotKeyFrameBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

class MissHotKeyManager;

/** Implementing MissHotKeyFrameBase */
class MissHotKeyFrame : public MissHotKeyFrameBase
{
    class MissHotKeyFrameImpl;
	public:
		/** Constructor */
		MissHotKeyFrame( wxWindow* parent, MissHotKeyManager* pData);

		virtual void OnListItemActivated( wxListEvent& event );
	//// end generated class members
	protected:
        void InitUI();

        bool GetHotkeyString(int nPlugin, int nFunc, wxString& strValue);

    private:
        shared_ptr<MissHotKeyFrameImpl> m_pImpl;
};

#endif // __MissHotKeyFrame__
