#ifndef __MissCoreOption__
#define __MissCoreOption__

/**
@file
Subclass of CoreOptionBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing CoreOptionBase */
class MissCoreOption : public CoreOptionBase
{
	public:
		/** Constructor */
		MissCoreOption( wxWindow* parent );
	//// end generated class members
	
};

#endif // __MissCoreOption__
