#ifndef __MISSPLUGINOPTION__
#define __MISSPLUGINOPTION__

/**
@file
Subclass of PluginOptionBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"
#include <memory>

class wxDataViewEvent;

/** Implementing PluginOptionBase */
class MissPluginOption : public PluginOptionBase
{
    class Impl;
public:
    MissPluginOption( wxWindow* parent );
    ~MissPluginOption();

protected:
    void InitUi();
    void BindEvent();
    void UnbindEvent();

protected:
    void OnFilterChoice( wxCommandEvent& event );
    void OnHotKeyItemActivated( wxDataViewEvent& event );
private:
    std::tr1::shared_ptr<Impl> m_pImpl;
};

#endif // __MISSPLUGINOPTION__
