#ifndef __MissWidget__
#define __MissWidget__

/**
@file
Subclass of MissWidgetBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissWidgetBase */
class MissWidget : public MissWidgetBase
{
	public:
		/** Constructor */
		MissWidget( wxWindow* parent );
	//// end generated class members

};

#endif // __MissWidget__
