#ifndef __MissWidgetFrame__
#define __MissWidgetFrame__

/**
@file
Subclass of MissWidgetFrameBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissWidgetFrameBase */
class MissWidgetFrame : public MissWidgetFrameBase
{
    class MissWidgetFrameImpl;
protected:
    // Handlers for MissWidgetFrameBase events.
    //void OnWidgetsListItemActivated( wxListEvent& event );
    virtual void OnWidgetsListTreeItemActivated( wxTreeEvent& event );
    void OnRunWidgetsListItemActivated( wxListEvent& event );
    void OnRunWidgetsListItemRightClick( wxListEvent& event );
public:
    /** Constructor */
    MissWidgetFrame( wxWindow* parent);
    //// end generated class members

protected:
    void InitUI();

private:
    shared_ptr<MissWidgetFrameImpl> m_pImpl;
};

#endif // __MissWidgetFrame__
