#ifndef __MissSetHotKey__
#define __MissSetHotKey__

/**
@file
Subclass of SetHotKeyBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing SetHotKeyBase */
class MissSetHotKey : public SetHotKeyBase
{
public:
    /** Constructor */
    MissSetHotKey(const wxString& strHotKey, wxWindow* parent);

    void GetHotKeyString(wxString& strHotKey);
    //// end generated class members

};

#endif // __MissSetHotKey__
